name: Deploy to Server

on:
  push:
    branches: 'master'
  workflow_dispatch:
  
jobs:
  build_bot:
    name: Build Bot
    runs-on: [self-hosted, discord-user]
    steps:
      - name: Pull Repo
        run: cd /home/zjxartcc_discord/rolebot && git pull
      - name: Install dependencies
        run: yarn
      - name: Build Bot
        run: tsc -p /home/zjxartcc_discord/rolebot/tsconfig.json
      - name: Run Bot
        run: pm2 restart rolebot --watch